/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalholab1;

import models.Clientes;
import Banco.Conector;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author gabrielrm
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        
         List<Clientes> clientesGeral = new ArrayList();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoPollos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadastra = new javax.swing.JMenuItem();
        jMenuItemListaClientes = new javax.swing.JMenuItem();
        jMenuItemListaFuncionarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNovoPedido = new javax.swing.JMenuItem();
        jMenuItemListaPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemVisualizaCardapio = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabelFundoPollos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pollosmin.png"))); // NOI18N
        getContentPane().add(jLabelFundoPollos);

        jMenu1.setText("Pessoas");

        jMenuItemCadastra.setText("Cadastrar");
        jMenuItemCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastraActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastra);

        jMenuItemListaClientes.setText("Listar Clientes");
        jMenuItemListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListaClientes);

        jMenuItemListaFuncionarios.setText("Listar Funcionários");
        jMenuItemListaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListaFuncionarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");

        jMenuItemNovoPedido.setText("Novo Pedido");
        jMenuItemNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNovoPedido);

        jMenuItemListaPedidos.setText("Listar Pedidos");
        jMenuItemListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemListaPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cardápio");
        jMenu3.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu3MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu3KeyPressed(evt);
            }
        });

        jMenuItemVisualizaCardapio.setText("Visualizar");
        jMenuItemVisualizaCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizaCardapioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemVisualizaCardapio);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sistema");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastraActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        cadastraPessoa form = new cadastraPessoa();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
            
    }//GEN-LAST:event_jMenuItemCadastraActionPerformed

    private void jMenuItemListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaClientesActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        listaClientes form = new listaClientes();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaClientesActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        //Aqui setamos para finalizar o programa
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenu3MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu3MenuKeyPressed
        
    }//GEN-LAST:event_jMenu3MenuKeyPressed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu3KeyPressed
        
    }//GEN-LAST:event_jMenu3KeyPressed

    private void jMenuItemVisualizaCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizaCardapioActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        cardapio form = new cardapio();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizaCardapioActionPerformed

    private void jMenuItemNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoPedidoActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        novoPedido form = new novoPedido();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemNovoPedidoActionPerformed

    private void jMenuItemListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaPedidosActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        listaPedidos form = new listaPedidos();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaPedidosActionPerformed

    private void jMenuItemListaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaFuncionariosActionPerformed
        //Chamamos nosso jframe e atribuimos a form
        listaFuncionarios form = new listaFuncionarios();
        //Aqui setamos para abrir no centro quando aberto
        form.setLocationRelativeTo(null);
        //Deixamos o jframe visivel
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Conector db = new Conector();
        db.clouseDataConnections();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoPollos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastra;
    private javax.swing.JMenuItem jMenuItemListaClientes;
    private javax.swing.JMenuItem jMenuItemListaFuncionarios;
    private javax.swing.JMenuItem jMenuItemListaPedidos;
    private javax.swing.JMenuItem jMenuItemNovoPedido;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVisualizaCardapio;
    // End of variables declaration//GEN-END:variables
}
